name: Java Build

on:
  workflow_call:
    inputs:
      container_image:
        type: string
        required: true              
      build_commands:
        type: string
        required: true
      artifact_paths:
        type: string
        required: true
      retention_days:
        type: number
        required: true
        default: 1
        
      

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.container_image }}
    steps:
      - uses: actions/checkout@v4

      - name: Build project
        run: ${{ inputs.build_commands }}
          
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ${{ inputs.artifact_paths }}
          retention-days: ${{ inputs.retention_days }}
